-- Preview: equipment updates from Updated-Table 1.csv
-- Read-only summary generated by generate_update.js
-- PostgreSQL

-- CSV rows total:              893
-- CSV mill/crusher excluded:   44
-- CSV duplicate fleet IDs:     4 (last row kept)
-- DB mill/crusher excluded:    38
-- Updates to apply:            845
-- Unmatched fleet IDs:         0
-- Duplicate fleet resolutions: 4
-- Unmatched company names:     0 (when equipment_companies.csv provided)
-- Registration conflicts:      6
-- VIN conflicts:               9

-- Duplicate fleet IDs in CSV (last row used)
--   2HGT789
--   2TMT866
--   2WTP770
--   2WTP793

-- Duplicate fleetId in DB (chosen row)
--   2WTP770: chose id cmn38agrw383fk42adib9hs80 (richest existing row, 2 rows)
--   2HGT789: chose id cmmyw76wi0scvk42a09x26n7k (richest existing row, 2 rows)
--   2WTP793: chose id cmn34nkzu2yw1k42almvf1d8v (richest existing row, 2 rows)
--   2TMT866: chose id cmp45evop1tc3p8casmsnqmhv (richest existing row, 2 rows)

-- Registration number conflicts within batch (same siteId)
--   1MML2, 3MMX428
--   2MLJ157, 2RAL525
--   1MMP206, 3MMX405
--   1MMP226, 2MKW324
--   3MMX407, 2MEJ779
--   3MMX418, 2PAT632

-- VIN conflicts within batch (same siteId)
--   1MML2, 1MML3
--   1MMJ26, 1MMJ27, 1MMJ28
--   2ASZ93, 2EXZ698
--   2RAL169, 2RAL532
--   2MLO260, 2MLN653
--   2RAZ352, 2UFZ762
--   2PAZ361, 2PAZ556
--   3MMX384, 3MMX390
--   2TMT686, 2TMT688

-- Sample changes (first 20)
-- 1MML1 (cmi8fy7nr0000skghr7hg7u8s)
--   type: null -> "LOADER"
--   make: null -> "Wulf Renoster"
--   model: null -> "Front End Loader"
--   location: null -> "OTHER"
--   companyName: null -> "Magaya Mining"
-- 1MML2 (cmi8fy7uf000kskghdn10kvoe)
--   type: null -> "LOADER"
--   make: null -> "Wulf Renoster"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AHF4219"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MML3 (cmi8fy7u2000eskghqkoq49iv)
--   type: null -> "LOADER"
--   make: null -> "Wulf Oliphant"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AGZ5340"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MML4 (cmi8fy7u0000bskghoalql60v)
--   type: null -> "LOADER"
--   make: null -> "XCGM"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AHE0277"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MML5 (cmi8fy7tn0008skghk7he2tz8)
--   registrationNumber: null -> "AHA2233"
--   location: "AMATOLA" -> "WALDEN"
--   companyName: "cmid6xprj000ijv02hs56t9r5" -> "Magaya Mining"
-- 1MML6 (cmi8fy7ud000hskghkdpb7yxe)
--   make: null -> "Wulf Renoster"
--   model: null -> "Front End Loader"
--   location: "AMATOLA" -> "WALDEN"
--   companyName: "cmid6xprj000ijv02hs56t9r5" -> "Magaya Mining"
-- 1MML7 (cmi8fy7uj000oskgh817jjd9a)
--   type: null -> "LOADER"
--   make: null -> "Wulf Renoster"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AGZ6672"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MML8 (cmi8fy7tn0007skgh7p1ya7ho)
--   type: null -> "LOADER"
--   make: null -> "XCGM"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AGZ8680"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MML9 (cmi8fy7uf000jskgho6gqd0mj)
--   type: null -> "LOADER"
--   make: null -> "Cat"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AGL7330"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MML10 (cmi8fy7u0000cskgh9xwpoxmj)
--   type: null -> "LOADER"
--   make: null -> "Cat"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AHA2792"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT11 (cmi8fy7u2000dskgh8qk6x236)
--   type: null -> "TIPPER"
--   make: null -> "Hohan N7B340"
--   model: null -> "Tipper Truck"
--   registrationNumber: null -> "AFQ3907"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT12 (cmi8fy7tn0009skghm7chy40y)
--   type: null -> "TIPPER"
--   make: null -> "Hohan N7B340"
--   model: null -> "Tipper Truck"
--   registrationNumber: null -> "AGL2425"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT13 (cmi8fy7xv0014skgh8rtrvmaq)
--   type: null -> "TIPPER"
--   make: null -> "Hohan N7B340"
--   model: null -> "Tipper Truck"
--   registrationNumber: null -> "AGZ8681"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT14 (cmi8fy7th0004skghyirduj5s)
--   type: null -> "TIPPER"
--   make: null -> "Howo 371"
--   model: null -> "Tipper Truck"
--   registrationNumber: null -> "AFQ8350"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT15 (cmi8fy7ue000iskghkz23lnyi)
--   type: null -> "TIPPER"
--   make: null -> "Howo 371"
--   model: null -> "Tipper Truck"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT16 (cmi8fy7vg000qskghu2dj1cxq)
--   registrationNumber: "AGJ0312" -> "AHA3999"
--   location: "AMATOLA" -> "WALDEN"
--   companyName: "cmid6xprj000ijv02hs56t9r5" -> "Magaya Mining"
-- 1MMT17 (cmi8fy7uh000nskgho663wcy0)
--   type: null -> "TIPPER"
--   make: null -> "Shacman F3000"
--   model: null -> "Tipper Truck"
--   registrationNumber: null -> "AGZ8655"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT18 (cmi8fy7tz000askghhi5qqyvg)
--   type: null -> "TIPPER"
--   make: null -> "Shacman F3000"
--   model: null -> "Tipper Truck"
--   registrationNumber: null -> "AFQ8351"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMP19 (cmi8fy7uh000mskghrj28cs9h)
--   type: null -> "POOL"
--   make: null -> "Toyota"
--   model: null -> "Mini Bus"
--   registrationNumber: null -> "AGJ1977"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMP20 (cmi8fy7u3000fskgh4hq1327i)
--   type: null -> "POOL"
--   make: null -> "Hino Dutro"
--   model: null -> "Small Truck"
--   registrationNumber: null -> "AHE 2201"
--   location: null -> "OTHER"
--   companyName: null -> "Magaya Mining"

-- Live DB checks (run against target database)

-- Companies in CSV not found in EquipmentCompany
WITH csv_companies(company_name) AS (
  VALUES
    ('All Solar Zim'),
    ('Alpha Transport'),
    ('Apex'),
    ('Auto Trans'),
    ('Benrique Reva Pvt Limited'),
    ('Bobo Investments'),
    ('Bousier Investment'),
    ('Bretlands'),
    ('Buenos  Dias Logistics'),
    ('CR7 Mine'),
    ('Connect Cut'),
    ('Continental'),
    ('Crebal'),
    ('Dale Brands'),
    ('Danda'),
    ('Deepsea Systems'),
    ('Detame  Cate Pvt'),
    ('EG Construction'),
    ('Earth Shift'),
    ('Earth shift'),
    ('EarthworX'),
    ('Esman'),
    ('First Quantum Resources'),
    ('Friendly Environment Services'),
    ('Gary Transport'),
    ('Gullifford Contractors'),
    ('Harveygood'),
    ('JJG International Trucks'),
    ('Jesmain'),
    ('Kan Horizon'),
    ('Kanevate Private Limited'),
    ('Kiwi Carter'),
    ('Krypton'),
    ('Latidoux Logistics'),
    ('Levante Resources'),
    ('LogiTrans'),
    ('M.Masoha'),
    ('Magaya Mining'),
    ('Maidei Chitsinde'),
    ('Makuku Logistics'),
    ('Mandebvu Contracting'),
    ('Merchain Logistics'),
    ('Methusela'),
    ('Millantus Enterprises'),
    ('Motsione Innovations'),
    ('Mount Solid'),
    ('Muvhuni Investments'),
    ('NT Transport'),
    ('Plant Africa'),
    ('Raventa'),
    ('Raventa (U Link)'),
    ('Rodam Incorporated'),
    ('Royal Ride'),
    ('SMD'),
    ('Sage Logistics'),
    ('Saymore Machoni'),
    ('Sharock Investment'),
    ('Simlex Coach'),
    ('Smac Construction'),
    ('Smba East'),
    ('TLS'),
    ('Tenrai Consortium'),
    ('Thinkstock Investments Pvt Ltd'),
    ('Tombest'),
    ('Try Sky'),
    ('U-Link Freight'),
    ('Uge'),
    ('Uptive Enterprises'),
    ('Urban Craft'),
    ('Vicemode Engineering'),
    ('Vision Star'),
    ('Webline'),
    ('Weston'),
    ('Willo & TH Safety'),
    ('Yingcan Investments'),
    ('Zim Earth'),
    ('Zipnac Investment')
)
SELECT cc.company_name
FROM csv_companies cc
WHERE NOT EXISTS (
  SELECT 1 FROM "EquipmentCompany" ec
  WHERE LOWER(TRIM(ec.name)) = LOWER(TRIM(cc.company_name))
)
ORDER BY 1;


-- Post-update registration uniqueness risks (same siteId, different equipment id)
SELECT e."siteId", e."registrationNumber", COUNT(*) AS cnt, array_agg(e."fleetId") AS fleet_ids
FROM "Equipment" e
WHERE e."registrationNumber" IS NOT NULL
  AND e.type NOT IN ('MILL', 'CRUSHER')
GROUP BY e."siteId", e."registrationNumber"
HAVING COUNT(*) > 1;
