-- Preview: equipment updates from Updated-Table 1.csv
-- Read-only summary generated by generate_update.js
-- PostgreSQL

-- CSV rows total:              888
-- CSV mill/crusher excluded:   43
-- CSV duplicate fleet IDs:     0 (best row kept)
-- DB mill/crusher excluded:    38
-- Updates to apply:            845
-- Unmatched fleet IDs:         0
-- Duplicate fleet resolutions: 0
-- Unmatched company names:     0 (when equipment_companies.csv provided)
-- Registration conflicts:      0
-- VIN conflicts:               0

-- Unique field conflicts auto-resolved (skipped field update on loser)
--   registrationNumber: AHF4219 -> kept 1MML2, skipped 3MMX428
--   registrationNumber: AGZ5340 -> kept 1MML3, skipped 2HGT895
--   registrationNumber: LTS4K -> kept 2MLJ157, skipped 2RAL525
--   registrationNumber: AGL7837 -> kept 1MMP206, skipped 3MMX405
--   registrationNumber: AGZ4796 -> kept 1MMP226, skipped 2MKW324
--   registrationNumber: AGJ8662 -> kept 2MEJ779, skipped 3MMX407
--   registrationNumber: AGJ8665 -> kept 2PAT632, skipped 3MMX418
--   registrationNumber: AGJ1977 -> kept 2HGT895, skipped 1MMP19
--   vinSerialId: 211058011 -> kept 1MML2, skipped 1MML3
--   vinSerialId: CD4045G178537 -> kept 1MMJ27, skipped 1MMJ26
--   vinSerialId: CD4045G178537 -> kept 1MMJ27, skipped 1MMJ28
--   vinSerialId: YN15506089 -> kept 2ASZ93, skipped 2EXZ698
--   vinSerialId: 86SL50L3NMN013816 -> kept 2RAL169, skipped 2RAL532
--   vinSerialId: BX14M00535 -> kept 2MLN653, skipped 2MLO260
--   vinSerialId: VCEC200DA00280844 -> kept 2RAZ352, skipped 2UFZ762
--   vinSerialId: LGC920EZPLC120716 -> kept 2PAZ361, skipped 2PAZ556
--   vinSerialId: 220922154 -> kept 3MMX384, skipped 3MMX390
--   vinSerialId: LZZ5ELSD0SN098462 -> kept 2TMT686, skipped 2TMT688
--   registrationNumber: AGL9344 -> kept 2SHT905, skipped 2JJIT359 (external holder (not in CSV batch))
--   vinSerialId: YV2JN50G46A61081 -> kept 2SHT905, skipped 2WTT749 (external holder (not in CSV batch))

-- Sample changes (first 20)
-- 1MML1 (cmi8fy7nr0000skghr7hg7u8s)
--   type: null -> "LOADER"
--   make: null -> "Wulf Renoster"
--   model: null -> "Front End Loader"
--   location: null -> "OTHER"
--   companyName: null -> "Magaya Mining"
-- 1MML2 (cmi8fy7uf000kskghdn10kvoe)
--   type: null -> "LOADER"
--   make: null -> "Wulf Renoster"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AHF4219"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MML3 (cmi8fy7u2000eskghqkoq49iv)
--   type: null -> "LOADER"
--   make: null -> "Wulf Oliphant"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AGZ5340"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MML4 (cmi8fy7u0000bskghoalql60v)
--   type: null -> "LOADER"
--   make: null -> "XCGM"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AHE0277"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MML5 (cmi8fy7tn0008skghk7he2tz8)
--   registrationNumber: null -> "AHA2233"
--   location: "AMATOLA" -> "WALDEN"
--   companyName: "cmid6xprj000ijv02hs56t9r5" -> "Magaya Mining"
-- 1MML6 (cmi8fy7ud000hskghkdpb7yxe)
--   make: null -> "Wulf Renoster"
--   model: null -> "Front End Loader"
--   location: "AMATOLA" -> "WALDEN"
--   companyName: "cmid6xprj000ijv02hs56t9r5" -> "Magaya Mining"
-- 1MML7 (cmi8fy7uj000oskgh817jjd9a)
--   type: null -> "LOADER"
--   make: null -> "Wulf Renoster"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AGZ6672"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MML8 (cmi8fy7tn0007skgh7p1ya7ho)
--   type: null -> "LOADER"
--   make: null -> "XCGM"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AGZ8680"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MML9 (cmi8fy7uf000jskgho6gqd0mj)
--   type: null -> "LOADER"
--   make: null -> "Cat"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AGL7330"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MML10 (cmi8fy7u0000cskgh9xwpoxmj)
--   type: null -> "LOADER"
--   make: null -> "Cat"
--   model: null -> "Front End Loader"
--   registrationNumber: null -> "AHA2792"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT11 (cmi8fy7u2000dskgh8qk6x236)
--   type: null -> "TIPPER"
--   make: null -> "Hohan N7B340"
--   model: null -> "Tipper Truck"
--   registrationNumber: null -> "AFQ3907"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT12 (cmi8fy7tn0009skghm7chy40y)
--   type: null -> "TIPPER"
--   make: null -> "Hohan N7B340"
--   model: null -> "Tipper Truck"
--   registrationNumber: null -> "AGL2425"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT13 (cmi8fy7xv0014skgh8rtrvmaq)
--   type: null -> "TIPPER"
--   make: null -> "Hohan N7B340"
--   model: null -> "Tipper Truck"
--   registrationNumber: null -> "AGZ8681"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT14 (cmi8fy7th0004skghyirduj5s)
--   type: null -> "TIPPER"
--   make: null -> "Howo 371"
--   model: null -> "Tipper Truck"
--   registrationNumber: null -> "AFQ8350"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT15 (cmi8fy7ue000iskghkz23lnyi)
--   type: null -> "TIPPER"
--   make: null -> "Howo 371"
--   model: null -> "Tipper Truck"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT16 (cmi8fy7vg000qskghu2dj1cxq)
--   registrationNumber: "AGJ0312" -> "AHA3999"
--   location: "AMATOLA" -> "WALDEN"
--   companyName: "cmid6xprj000ijv02hs56t9r5" -> "Magaya Mining"
-- 1MMT17 (cmi8fy7uh000nskgho663wcy0)
--   type: null -> "TIPPER"
--   make: null -> "Shacman F3000"
--   model: null -> "Tipper Truck"
--   registrationNumber: null -> "AGZ8655"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMT18 (cmi8fy7tz000askghhi5qqyvg)
--   type: null -> "TIPPER"
--   make: null -> "Shacman F3000"
--   model: null -> "Tipper Truck"
--   registrationNumber: null -> "AFQ8351"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMP19 (cmi8fy7uh000mskghrj28cs9h)
--   type: null -> "POOL"
--   make: null -> "Toyota"
--   model: null -> "Mini Bus"
--   location: null -> "WALDEN"
--   companyName: null -> "Magaya Mining"
-- 1MMP20 (cmi8fy7u3000fskgh4hq1327i)
--   type: null -> "POOL"
--   make: null -> "Hino Dutro"
--   model: null -> "Small Truck"
--   registrationNumber: null -> "AHE 2201"
--   location: null -> "OTHER"
--   companyName: null -> "Magaya Mining"

-- Live DB checks (run against target database)

-- Companies in CSV not found in EquipmentCompany
WITH csv_companies(company_name) AS (
  VALUES
    ('All Solar Zim'),
    ('Alpha Transport'),
    ('Apex'),
    ('Auto Trans'),
    ('Benrique Reva Pvt Limited'),
    ('Bobo Investments'),
    ('Bousier Investment'),
    ('Bretlands'),
    ('Buenos  Dias Logistics'),
    ('CR7 Mine'),
    ('Connect Cut'),
    ('Continental'),
    ('Crebal'),
    ('Dale Brands'),
    ('Danda'),
    ('Deepsea Systems'),
    ('Detame  Cate Pvt'),
    ('EG Construction'),
    ('Earth Shift'),
    ('EarthworX'),
    ('Esman'),
    ('First Quantum Resources'),
    ('Friendly Environment Services'),
    ('Gary Transport'),
    ('Gullifford Contractors'),
    ('HarvGood'),
    ('JJG International Trucks'),
    ('Jesmain'),
    ('Kan Horizon'),
    ('Kanevate Private Limited'),
    ('Kiwi Carter'),
    ('Krypton'),
    ('Latidoux Logistics'),
    ('Levante Resources'),
    ('Logi Trans'),
    ('M.Masoha'),
    ('Magaya Mining'),
    ('Maidei Chitsinde'),
    ('Makuku Logistics'),
    ('Mandebvu Contracting'),
    ('Merchain Logistics'),
    ('Methusela'),
    ('Millantus Enterprises'),
    ('Motsione Innovations'),
    ('Mount Solid'),
    ('Muvhuni Investments'),
    ('NT Transport'),
    ('Plant Africa'),
    ('Raventa'),
    ('Raventa (U Link)'),
    ('Rodam Incorporated'),
    ('Royal Ride'),
    ('SMD'),
    ('Sage Logistics'),
    ('Saymore Machoni'),
    ('Sharock Investment'),
    ('Simlex Coach'),
    ('Smac Construction'),
    ('Smba East'),
    ('TLS'),
    ('Tenrai Consortium'),
    ('Thinkstock Investments Pvt Ltd'),
    ('Tombest'),
    ('Try Sky'),
    ('U-freight link'),
    ('Uge'),
    ('Uptive Enterprises'),
    ('Urban Craft'),
    ('Vicemode Engineering'),
    ('Vision Star'),
    ('Webline'),
    ('Weston'),
    ('Willo & TH Safety'),
    ('Yingcan Investments'),
    ('Zim Earth'),
    ('Zipnac Investment')
)
SELECT cc.company_name
FROM csv_companies cc
WHERE NOT EXISTS (
  SELECT 1 FROM "EquipmentCompany" ec
  WHERE LOWER(TRIM(ec.name)) = LOWER(TRIM(cc.company_name))
)
ORDER BY 1;


-- Post-update registration uniqueness risks (same siteId, different equipment id)
SELECT e."siteId", e."registrationNumber", COUNT(*) AS cnt, array_agg(e."fleetId") AS fleet_ids
FROM "Equipment" e
WHERE e."registrationNumber" IS NOT NULL
  AND (e.type IS NULL OR e.type NOT IN ('MILL', 'CRUSHER'))
GROUP BY e."siteId", e."registrationNumber"
HAVING COUNT(*) > 1;
